Adjust svc_vc_null() definition to avoid clang 15 warning
With clang 15, the following -Werror warning is produced:

    sys/rpc/svc_vc.c:1078:12: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
    svc_vc_null()
               ^
                void

This is because svc_vc_null() is declared with a (void) argument list,
but defined with an empty argument list. Make the definition match the
declaration.

MFC after:	3 days

(cherry picked from commit 87d18efef7e3df5f4475cfe1a8f6d6782b7c1527)